### ISSUE TITLE
Installing MFC in ubuntu

### ISSUE THREAD

**Issue by syam-s** [MFlowCode/MFC#41] opened 2022-11-15 07:07 UTC
Hi MFC team, 
I am new to MFC and I have some difficulties in installing MFC into me Ubuntu. It would be very helpful, if you could provide instructions to install MFC in a linux system. I have read the documentation, but installation was unsuccessful. Looking forward to hear from you. Thank you.

**Comment by henryleberre** [comment] 2022-11-15 07:17
Hello Syam, documentation on how to build and install MFC can be found under [doc/documentation/building.md](https://github.com/henryleberre/MFC/blob/master/doc/documentation/building.md) or [on our website](https://mflowcode.github.io/documentation/md_building.html).

If you are still getting an error, please post what you have tried and what error you are receiving so we can better assist you!

**Comment by syam-s** [comment] 2022-11-15 10:31
Thank you and I appreciate your swift response.  I will get back to you soon.

**Comment by henryleberre** [comment] 2022-11-22 00:46
@syam-s are you still having trouble building MFC ?

**Comment by syam-s** [comment] 2022-11-23 14:10
Sorry for the delay in the response @henryleberre...

I am still facing some issues. The errors I am having are at the end of the installation and are pasted below,
_________________________________________________________________________
CMake Error: Problem with archive_read_open_file(): Unrecognized archive format
CMake Error: Problem extracting tar: /home/syams/Downloads/MFC/build/fftw/fftw-prefix/src/fftw-3.3.10.tar.gz
-- extracting... [error clean up]
CMake Error at fftw-stamp/extract-fftw.cmake:33 (message):
  error: extract of
  '/home/syams/Downloads/MFC/build/fftw/fftw-prefix/src/fftw-3.3.10.tar.gz'
  failed


gmake[3]: *** [CMakeFiles/fftw.dir/build.make:100: fftw-prefix/src/fftw-stamp/fftw-download] Error 1
gmake[2]: *** [CMakeFiles/Makefile2:83: CMakeFiles/fftw.dir/all] Error 2
gmake[1]: *** [CMakeFiles/Makefile2:90: CMakeFiles/fftw.dir/rule] Error 2
gmake: *** [Makefile:124: fftw] Error 2


Error: Failed to build the fftw target.

Terminated
mfc: Exiting the Python virtual environment.
_______________________________________________________________________________

Please comment,  your thought on these issues.

**Comment by syam-s** [comment] 2022-11-24 07:32
I also tried to install MGC with CMake and I am getting this error,

xxxxxxxx~/Downloads/MFC-4.1.2$ cmake .
-- The C compiler identification is GNU 11.3.0
-- The CXX compiler identification is GNU 11.3.0
-- The Fortran compiler identification is GNU 11.3.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Detecting Fortran compiler ABI info
-- Detecting Fortran compiler ABI info - done
-- Check for working Fortran compiler: /usr/bin/gfortran - skipped
CMake Error at CMakeLists.txt:55 (find_program):
  Could not find FYPP_EXE using the following names: fypp


-- Configuring incomplete, errors occurred!
See also "/xxxxxxxx/Downloads/MFC-4.1.2/CMakeFiles/CMakeOutput.log".
xxxxxxxx:~/Downloads/MFC-4.1.2$

**Comment by henryleberre** [comment] 2022-11-24 08:15
@syam-s Could you try running:
```console
$ sudo apt update
$ sudo apt upgrade
$ sudo apt install tar wget make cmake gcc g++ \
                   python3 python3-dev         \
                   "openmpi-*" libopenmpi-dev
```
(from https://mflowcode.github.io/documentation/md_building.html)

Notice that `tar` is a dependency. I am guessing that CMake can't find `tar` to untar the FFTW source archive. 

If you want to run CMake manually, you will have to install Fypp using `pip3 install fypp`. We use it to pre-process Fortran source files.

I hope this resolves your issue!

**Comment by syam-s** [comment] 2022-11-24 08:57
$ sudo apt update
$ sudo apt upgrade
$ sudo apt install tar wget make cmake gcc g++ \
                   python3 python3-dev         \
                   "openmpi-*" libopenmpi-dev

I am getting the same error after following the above instructions. I have checked the availability of the file in the destination folder and found "fftw-3.3.10.tar.gz" there. When I tried to untar the file I received the error below,

/Downloads/MFC/build/fftw/fftw-prefix/src$ tar -xvzf fftw-3.3.10.tar.gz 

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now

Then I downloaded it from "http://www.fftw.org/fftw-3.3.10.tar.gz" and extracted it. The extraction process worked. I think there is an issue with the "fftw-3.3.10.tar.gz" file present at the "MFC/build/fftw/fftw-prefix/src".



Also, please instruct me on how to install with CMakeList.txt too.

**Comment by syam-s** [comment] 2022-11-24 10:34
$ sudo apt update
$ sudo apt upgrade
$ sudo apt install tar wget make cmake gcc g++ \
                   python3 python3-dev         \
                   "openmpi-*" libopenmpi-dev

I am getting the same error after following the above instructions. I have checked the availability of the file in the destination folder and found "fftw-3.3.10.tar.gz" there. When I tried to untar the file I received the error below,

/Downloads/MFC/build/fftw/fftw-prefix/src$ tar -xvzf fftw-3.3.10.tar.gz 

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now

Then I downloaded it from "http://www.fftw.org/fftw-3.3.10.tar.gz" and extracted it. The extraction process worked. I think there is an issue with the "fftw-3.3.10.tar.gz" file present at the "MFC/build/fftw/fftw-prefix/src".



Also, please instruct me on how to install with CMakeList.txt too.

**Comment by henryleberre** [comment] 2022-11-24 16:40
This error is interesting, I have never seen it before. The archive appears to be corrupted. I apologize you ran into this issue.

### Solution 1

```console
$ rm -rf build/fftw
$ ./mfc.sh build <your arguments here - if any>
```

This will give CMake another chance at downloading and extracting the FFTW source archive. It will then proceed as usual.

### Solution 2

Replace `/Downloads/MFC/build/fftw/fftw-prefix/src/fftw-3.3.10.tar.gz` with the archive you downloaded (and were able to extract successfully).

### Solution 3

```
$ sudo apt install libfftw3-dev
$ rm -rf build/fftw
$ ./mfc.sh build <your arguments here - if any> --no-fftw
```

It requests that MFC not download and install FFTW from source. It will instead search for a version already installed on your system (e.g from `sudo apt install libfftw3-dev`).

### Building without `mfc.sh` (not recommended)

The error isn't with `mfc.sh` itself so **I wouldn't advise using CMake directly**, as you lose the ability to _easily_ run cases and test MFC. Building MFC (and not its dependencies: Silo and FFTW) can be done via

```
rm -rf build && cmake -B build -S . -DMFC_BUILD_ALL=ON
```

You will have to manually install FFTW (if you want to build Simulation or Post-Process) and Silo (for Post-Process). `mfc.sh` uses the CMake super-build file from [toolchain/dependencies/CMakeLists.txt](toolchain/dependencies/CMakeLists.txt).

Please let me know if this resolves your issue (or not) !

**Comment by syam-s** [comment] 2022-11-25 09:45
Good news @henryleberre...

I have tried Solutions 1 & 2, but they didn't work.

So, I have tried to find where the "fftw-3.3.10.tar.gz" downloading command comes from. I have found that the downloading link is given in the "MFC/toolchain/dependencies". Then I checked the "fftw-3.3.10.tar.gz" repository link, which is given in the dependencies file was "http://www.fftw.org/fftw-3.3.10.tar.gz". Even though  I could download the file from this link and extract it manually, the actual public release link is not this. The real link for the public release is "https://fftw.org/pub/fftw/fftw-3.3.10.tar.gz". Then I edited the  "MFC/toolchain/dependencies" file and replaced the old link with the new one. After saving the file, I followed the Solution 1 instruction. Finally, the MFC build was successful and finished without any errors.

So, please check the  "MFC/toolchain/dependencies" file and make suitable changes if t is a real issue for everyone. If it is only my issue, please ignore the suggestion. 

@henryleberre, thank you for your support and swift replies in solving this issue. I am looking forward to exploring MFC capabilities and trying to use for my research work.

Thank you MFC team.

**Comment by henryleberre** [comment] 2022-11-26 17:03
Thank you for the update @syam-s. I am unable to reproduce the issue you faced with downloading the FFTW source archive. I originally obtained the link from http://www.fftw.org/download.html. If others encounter this issue in the future, I will take a closer look. We build on many different systems and we have never seen this before..

We are looking forward to reading about your research using MFC!

I am closing this issue as "can't reproduce" for now so it can be reopened if we can.

**Closed by henryleberre** 2022-11-26 17:03 UTC
