### ISSUE TITLE
Use of Pinned Memory for Faster CPU/GPU Bandwidth

### ISSUE THREAD

**Issue by max-Hawkins** [MFlowCode/MFC#683] opened 2024-11-05 15:27 UTC
I'm curious why MFC doesn't use pinned memory (see [here](https://stackoverflow.com/questions/5736968/why-is-cuda-pinned-memory-so-fast) for more info). Pinned host memory means that it will *always* be resident in RAM and cannot be paged out. This provides ensurances that enable faster memory transactions involving this memory region. 

There is a command line flag for OpenACC to pin host memory for the entire application, and older OpenACC references mention a per-variable 'pinned' flag. In my minimal testing, I only got the first method to work. This led to increased CPU/GPU bandwidth as expected (~4GB/s to ~12GB/s for a V100 test). My thought is that this would be beneficial for I/O when we transfer to the CPU first for GPU jobs.

Change in CMakeLists.txt for the application-wide pinned memory:
>  PRIVATE -gpu=keep,ptxinfo,lineinfo,pinned

@henryleberre Is there some weird compiler issue I'm unaware of that would keep this from being added?

**Comment by sbryngelson** [comment] 2024-11-11 02:11
This seems like a good idea. We can add it to the NVHPC compiler flags and CI will make sure it runs. For CCE + AMD GPUs I'm not sure if this will work (@abbotts might know). You can open a PR to try it out.

**Comment by sbryngelson** [comment] 2024-11-11 18:04
Apparently this doesn't work (private convo. w/ @max-Hawkins). closing..

**Comment by max-Hawkins** [comment] 2024-11-11 18:35
It's not that it doesn't 'work' per say but rather that it necessitates considerations of the CPU memory usage - especially with multiple processes per CPU. If you have 8 GPUs each with 80GB of memory attached to a CPU with 0.5 TB of memory, you're gonna get OOM. Pinning memory via a global compiler flag means whatever memory we allocate with OpenACC takes up CPU memory. A per-variable flag would be much better as we really only communicate a small subset of GPU data back to the CPU frequently (halo, I/O, etc).

**Comment by sbryngelson** [comment] 2024-11-11 19:17
Let me reopen this for the moment, then, until we have more formal closure on this.

**Comment by abbotts** [comment] 2024-11-12 14:45
CCE doesn't have any compiler flags to pin all memory (although we have managed/unified flags). We *do* have a pinned allocator trait in OpenMP, but not in OpenACC since OpenACC doesn't support that yet.

Probably the easiest way to implement this selectively would be to use cudaHostRegister/hipHostRegister on the host-side buffers you intend to frequently pass data between. If you can pinpoint places where you're bandwidth limited it might be worth experimenting.

I'll note that most large machines are diskless and there don't have an ability to swap, so the oom scenario you're describing @max-Hawkins isn't normally an option at computing centers (though for workstation users it's a real possibility).

The downside to pinning all allocations on diskless nodes would be that page-locking takes some time so the allocation statements themselves take longer (using xxxHostRegister would defer that cost until the register call). The advantage is knowing that the memory is page locked allows the runtime to more aggressively DMA, because there's no chance that a page will move (even within memory) while it's copying.

Finally, if you're worried about this for I/O costs I think it's worth mentioning that *on Frontier specifically* you can pass GPU memory directly into any parallel I/O call that uses MPI-IO (phdf5, pnetcdf, mpi-io itself) so long as GPU aware MPI is supported and you don't have to bounce through the host first.

**Comment by max-Hawkins** [comment] 2024-11-12 15:40
@abbotts Thanks for all that information. That's unfortunate about CCE, and looks like even for NVHPC/CUDA builds, we have to use CUDA Fortran if we want this feature on a per-variable basis then.
We were looking at this due to some performance issues Anand R was seeing on NCSA Delta machines.

**Comment by sbryngelson** [comment] 2024-11-12 15:44
> @abbotts Thanks for all that information. That's unfortunate about CCE, and looks like even for NVHPC/CUDA builds, we have to use CUDA Fortran if we want this feature on a per-variable basis then. We were looking at this due to some performance issues Anand R was seeing on NCSA Delta machines.

Is that what this issue was for? If so, we should close it as that is a performance regression (if it's not just a mistake, which also appears possible).

**Comment by max-Hawkins** [comment] 2024-11-12 15:49
This is motivated by some of my work as well, but I was just going to shelve this until Anand brought up his problem. Close it if you want. It can get figured out when people actually feel they need that extra performance. I just thought that might be now since Anand brought it up.

**Closed** 2024-11-12 15:51 UTC
Labels: enhancement, question
